[package]
name = "eve_commander"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main" }

[addresses]
eve_commander = "0x0"
